---
 execution:
   - concurrency: 50
     ramp-up: 2m
     hold-for: 60m
     scenario:
       script: ./loadtest/jpetstore.jmx
       properties:
           hostname: 10.226.181.67
       data-sources:
       - path: ./loadtest/logins.csv
         delimiter: ';'
         quoted: false
         loop: true
         variable-names: login,password
         random-order: false

 services:
 - module: passfail
   criteria:
   - avg-rt>10ms for 7s, stop as failed
   - hits of reserve >10 for 13s, continue as failed
